spring.application.name=smart-grievance

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/smart_grievance
spring.datasource.username=root
spring.datasource.password=ajaymc@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true